// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// `FlutterFire` configuration options.
///
/// This file was generated by `flutterfire configure` and should be committed to version control.
/// It contains the platform-specific Firebase configuration for your Flutter app.
///
/// To regenerate this file, run `flutterfire configure` again and make sure to update
/// the `google-services.json` and `GoogleService-Info.plist` files in your Flutter project.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // For now, return a placeholder configuration
    // This will be replaced with actual Firebase config during setup
    return const FirebaseOptions(
      apiKey: 'YOUR_API_KEY',
      appId: 'YOUR_APP_ID',
      messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
      projectId: 'yourwish-chess',
      authDomain: 'yourwish-chess.firebaseapp.com',
      databaseURL: 'https://yourwish-chess.firebaseio.com',
      storageBucket: 'yourwish-chess.appspot.com',
      iosBundleId: 'com.yourwish.chess',
      androidPackageName: 'com.yourwish.chess',
    );
  }
}
